export const FullTime = [
  "Performance-based bonus should not be declared as part of a salary but must be indicated in the incentives/ perks/ bonus column. ESOP (Employee Stock Option Plan) and lock-in period, if any, should be stated explicitly in additional information.",
  "Any amount to be disbursed later than the end of first 12 months should not be a part of Gross/CTC. Statutory annual pay-outs (e.g. Medical, LTC etc.) should not be a part of Gross.",
  "It may be noted that IITs have maintained a high rank in many surveys done by many organisations, wherein several departments have achieved the best positions nationally and internationally as well. The recognition could not have been possible without your support. We are once again striving to strengthen our position in Rankings wherein, a team of survey ranking committee may contact you to ask some queries. For example\na. To nominate up to 10 institutions that they rate as being the best for producing graduates.\nb. To nominate up to 30 international institutions outside of their country/territory of knowledge that they rate as being the best for Producing graduates.\nWe request you to respond whenever contacted by such ranking agencies/organizations.",
  "All the correspondences pre- and post-selection should be routed through Placement Cell of IIT Indore.",
  "The offer letter should be released within 30 days of result declaration. It must contain Date of Joining, Location, detailed breakup of salary structure based on the filled CTC in the JAF. Under any circumstances, the offer letter should not be delayed beyond March. Joining date should not be deferred beyond 1st September.",
  "Recruiter must abide by the information filled in JAF as above and AIPC Guidelines to the Recruiters (https://aipciits.com/guidelines/).",
  "Companies are welcome to come for recruiting multiple times if interested or for any other special recruitment drive.",
  "Companies on campus are advised not to engage in any off-campus recruitment activity before/during/after the campus process. For any issues, the company should contact the placement cell of the IIT Indore.",
  "Same CTC for the same job profile and role should be offered across all IITs.",
  "It is strongly recommended to keep some students in waitlist in addition to your final selection.",
  "If in case of any discrepancy in the final offers, the company would be liable for strict action as per AIPC guidelines and the respective IIT placement policy. If a company is unable to honour the offered position or delays the joining of the candidate beyond September 2025, the selected candidate is entitled to compensation equal to three months of salary, as specified in the JAF or the offer letter, whichever amount is higher. Companies/ organizations withdrawing offers without compensation will be paused from Phase-1 full-time hiring by all IITs. They may also be debarred or black-listed depending on the nature of JAF violations, as per the guidelines of AIPC.",
];

export const Intern = [
  "It may be noted that IITs have maintained a high rank in many surveys done by many organizations, wherein several departments have achieved the best positions nationally and internationally as well. The recognition could not have been possible without your support. We are once again striving to strengthen our position in Rankings wherein, a team of survey ranking committee may contact you to ask some queries. For example\na. To nominate up to 10 institutions that they rate as being the best for producing graduates.\nb. To nominate up to 30 international institutions outside of their country/territory of knowledge that they rate as being the best for Producing graduates.\nIIT Indore requests you to respond whenever contacted by such ranking agencies/organizations.",
  "Recruiter must abide by the information filled in JAF as above and AIPC Guidelines to the Recruiters (https://aipciits.com/guidelines/).",
  "After successful completion of the internship, it is highly desirable that the status of the PPOs be informed within two weeks of the completion of the internship and preferably not later than 15th September 2027 (for 2 months internship). Companies are advised to leverage PPO instead of PPI as the latter does not provide significant benefits either to students or companies.",
  "Companies on campus are advised not to engage in any off-campus activity before/after the campus process. For any issues the company should contact the Placement Cell of the IIT Indore.",
  "Same stipend for the same internship profile and role across all IITs.",
  "It is strongly recommended to keep some students in waitlist in addition to your final selection.",
  "If in case of any discrepancy in the final offers, the company would be liable for strict action as per AIPC guidelines and the respective IIT placement policy. In case a company is not in a position to honour the offer made, reducing the stipend or delay in joining, suitable action may be taken against the recruiter depending on the nature of JAF violations, as per the guidelines of AIPC and IIT Indore.",
];